### ISSUE TITLE
Updated version?

### ISSUE THREAD

**Issue by pldavid2** [TetzkatLipHoka/VideoCompareGUI#1]
Hello, found this and looks promising. Do you have maybe an updated release? 
I notice that in the readme picture that the "shift" is enabled and there are icons in the topbar, but those features are not available in the exe available here https://github.com/TetzkatLipHoka/VideoCompareGUI/releases/tag/v1.0.0.0
Thank you

**Comment by TetzkatLipHoka** [comment]
"Shift" was actually broken, guess I forgot to rebuild before packing as there is no reason for it being disabled.
The Icons are from another application for "Window Management" and are not part of this Software ;)
I just made/published an Update for the latest VideoCompare Version tho.

**Comment by pldavid2** [comment]
Thank you works great! Is it ok if i mention your GUI on the video-compare repository? I think it will be useful for others too.

**Comment by TetzkatLipHoka** [comment]
Sure, I dont mind.
